spring:
  application:
    name: service-registry
server:
  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

logging:
  level:
    com.netflix.eureka: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
